/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package podcast.api.kotlin.demo

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testPlaceholder() {
    }
}
