// Generated by listennotes/devtools/api-sdks/sync.py kotlin. Do not edit.
package podcast.api.kotlin.demo

import com.listennotes.podcast_api.Client
import com.listennotes.podcast_api.ApiResponse

object GeneratedExamples {
    fun search(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("q", "star wars")
        parameters.put("sort_by_date", "0")
        parameters.put("type", "episode")
        parameters.put("offset", "0")
        parameters.put("len_min", "10")
        parameters.put("len_max", "30")
        parameters.put("genre_ids", "68,82")
        parameters.put("published_before", "1580172454000")
        parameters.put("published_after", "0")
        parameters.put("only_in", "title,description")
        parameters.put("language", "English")
        parameters.put("region", "")
        parameters.put("safe_mode", "0")
        parameters.put("unique_podcasts", "0")
        parameters.put("interviews_only", "0")
        parameters.put("sponsored_only", "0")
        parameters.put("page_size", "10")
        return client.search(parameters)
    }

    fun typeahead(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("q", "star wars")
        parameters.put("show_podcasts", "1")
        parameters.put("show_genres", "1")
        parameters.put("safe_mode", "0")
        return client.typeahead(parameters)
    }

    fun searchEpisodeTitles(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("q", "Jerusalem Demsas on The Dispossessed")
        return client.searchEpisodeTitles(parameters)
    }

    fun spellcheck(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("q", "microsft stock")
        return client.spellcheck(parameters)
    }

    fun getRelatedSearches(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("q", "evergrande")
        return client.fetchRelatedSearches(parameters)
    }

    fun getTrendingSearches(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        return client.fetchTrendingSearches(parameters)
    }

    fun getBestPodcasts(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("genre_id", "93")
        parameters.put("page", "2")
        parameters.put("region", "us")
        parameters.put("sort", "listen_score")
        parameters.put("safe_mode", "0")
        return client.fetchBestPodcasts(parameters)
    }

    fun getPodcastById(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("id", "4d3fe717742d4963a85562e9f84d8c79")
        parameters.put("next_episode_pub_date", "1479154463000")
        parameters.put("sort", "recent_first")
        return client.fetchPodcastById(parameters)
    }

    fun deletePodcastById(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("id", "4d3fe717742d4963a85562e9f84d8c79")
        parameters.put("reason", "the podcaster wants to delete it")
        return client.deletePodcast(parameters)
    }

    fun getEpisodeById(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("id", "6b6d65930c5a4f71b254465871fed370")
        parameters.put("show_transcript", "1")
        return client.fetchEpisodeById(parameters)
    }

    fun getEpisodesInBatch(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("ids", "c577d55b2b2b483c969fae3ceb58e362,0f34a9099579490993eec9e8c8cebb82")
        return client.batchFetchEpisodes(parameters)
    }

    fun getPodcastsInBatch(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("ids", "3302bc71139541baa46ecb27dbf6071a,68faf62be97149c280ebcc25178aa731,37589a3e121e40debe4cef3d9638932a,9cf19c590ff0484d97b18b329fed0c6a")
        parameters.put("rsses", "https://rss.art19.com/recode-decode,https://rss.art19.com/the-daily,https://www.npr.org/rss/podcast.php?id=510331,https://www.npr.org/rss/podcast.php?id=510331")
        parameters.put("itunes_ids", "1457514703,1386234384,659155419")
        parameters.put("spotify_ids", "3DDfEsKDIDrTlnPOiG4ZF4,4qDNe5Gvl1XxdLinUGEXrC,23NZCM4ik6o3UYkM473Itz")
        parameters.put("show_latest_episodes", "1")
        parameters.put("next_episode_pub_date", "1557394247000")
        return client.batchFetchPodcasts(parameters)
    }

    fun getCuratedPodcastById(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("id", "SDFKduyJ47r")
        return client.fetchCuratedPodcastsListById(parameters)
    }

    fun getGenres(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("top_level_only", "1")
        return client.fetchPodcastGenres(parameters)
    }

    fun getRegions(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        return client.fetchPodcastRegions(parameters)
    }

    fun getLanguages(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        return client.fetchPodcastLanguages(parameters)
    }

    fun justListen(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        return client.justListen(parameters)
    }

    fun getCuratedPodcasts(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("page", "2")
        return client.fetchCuratedPodcastsLists(parameters)
    }

    fun getPodcastRecommendations(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("id", "25212ac3c53240a880dd5032e547047b")
        parameters.put("safe_mode", "0")
        return client.fetchRecommendationsForPodcast(parameters)
    }

    fun getEpisodeRecommendations(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("id", "254444fa6cf64a43a95292a70eb6869b")
        parameters.put("safe_mode", "0")
        return client.fetchRecommendationsForEpisode(parameters)
    }

    fun submitPodcast(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("rss", "https://feeds.megaphone.fm/committed")
        parameters.put("email", "hello@example.com")
        return client.submitPodcast(parameters)
    }

    fun getPlaylistById(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("id", "m1pe7z60bsw")
        parameters.put("type", "episode_list")
        parameters.put("last_timestamp_ms", "0")
        parameters.put("sort", "recent_added_first")
        return client.fetchPlaylistById(parameters)
    }

    fun getPlaylists(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("sort", "recent_added_first")
        parameters.put("page", "1")
        return client.fetchMyPlaylists(parameters)
    }

    fun getPodcastAudience(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("id", "25212ac3c53240a880dd5032e547047b")
        return client.fetchAudienceForPodcast(parameters)
    }

    fun getPodcastsByDomainName(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("domain_name", "nytimes.com")
        parameters.put("page", "1")
        return client.fetchPodcastsByDomain(parameters)
    }

    fun createPlaylist(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("name", "My favorite podcasts")
        parameters.put("description", "Podcasts and episodes to revisit.")
        parameters.put("visibility", "public")
        parameters.put("type", "episode_list")
        return client.createPlaylist(parameters)
    }

    fun updatePlaylist(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("id", "m1pe7z60bsw")
        parameters.put("name", "My favorite podcasts")
        parameters.put("description", "Podcasts and episodes to revisit.")
        parameters.put("visibility", "public")
        parameters.put("type", "podcast_list")
        return client.updatePlaylist(parameters)
    }

    fun deletePlaylist(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("id", "m1pe7z60bsw")
        return client.deletePlaylist(parameters)
    }

    fun addPlaylistItem(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("id", "m1pe7z60bsw")
        parameters.put("episode_id", "e53e6992a5b7492f9ea6fcd85d9ad95f")
        parameters.put("notes", "Worth a listen.")
        return client.addPlaylistItem(parameters)
    }

    fun deletePlaylistItem(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("id", "m1pe7z60bsw")
        parameters.put("item_id", "23")
        return client.deletePlaylistItem(parameters)
    }

    fun updatePlaylistItemNotes(client: Client): ApiResponse {
        val parameters = HashMap<String, String>()
        parameters.put("id", "m1pe7z60bsw")
        parameters.put("item_id", "23")
        parameters.put("notes", "")
        return client.updatePlaylistItemNotes(parameters)
    }

    fun call(client: Client, operation: String, parameters: Map<String, String>): ApiResponse =
        when (operation) {
            "search" -> client.search(parameters)
            "typeahead" -> client.typeahead(parameters)
            "searchEpisodeTitles" -> client.searchEpisodeTitles(parameters)
            "spellcheck" -> client.spellcheck(parameters)
            "getRelatedSearches" -> client.fetchRelatedSearches(parameters)
            "getTrendingSearches" -> client.fetchTrendingSearches(parameters)
            "getBestPodcasts" -> client.fetchBestPodcasts(parameters)
            "getPodcastById" -> client.fetchPodcastById(parameters)
            "deletePodcastById" -> client.deletePodcast(parameters)
            "getEpisodeById" -> client.fetchEpisodeById(parameters)
            "getEpisodesInBatch" -> client.batchFetchEpisodes(parameters)
            "getPodcastsInBatch" -> client.batchFetchPodcasts(parameters)
            "getCuratedPodcastById" -> client.fetchCuratedPodcastsListById(parameters)
            "getGenres" -> client.fetchPodcastGenres(parameters)
            "getRegions" -> client.fetchPodcastRegions(parameters)
            "getLanguages" -> client.fetchPodcastLanguages(parameters)
            "justListen" -> client.justListen(parameters)
            "getCuratedPodcasts" -> client.fetchCuratedPodcastsLists(parameters)
            "getPodcastRecommendations" -> client.fetchRecommendationsForPodcast(parameters)
            "getEpisodeRecommendations" -> client.fetchRecommendationsForEpisode(parameters)
            "submitPodcast" -> client.submitPodcast(parameters)
            "getPlaylistById" -> client.fetchPlaylistById(parameters)
            "getPlaylists" -> client.fetchMyPlaylists(parameters)
            "getPodcastAudience" -> client.fetchAudienceForPodcast(parameters)
            "getPodcastsByDomainName" -> client.fetchPodcastsByDomain(parameters)
            "createPlaylist" -> client.createPlaylist(parameters)
            "updatePlaylist" -> client.updatePlaylist(parameters)
            "deletePlaylist" -> client.deletePlaylist(parameters)
            "addPlaylistItem" -> client.addPlaylistItem(parameters)
            "deletePlaylistItem" -> client.deletePlaylistItem(parameters)
            "updatePlaylistItemNotes" -> client.updatePlaylistItemNotes(parameters)
            else -> error("Unknown operation: $operation")
        }
}
